PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?d
WHERE {
 ?x a owl:ObjectProperty .
 ?y a owl:ObjectProperty .
 ?x rdfs:domain ?d .
 ?y rdfs:domain ?d .
FILTER ( ?x != ?y )
}