PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX lgd: <http://linkedgeodata.org/>
PREFIX lgdo: <http://linkedgeodata.org/ontology/>

SELECT *
WHERE {
?country a lgdo:Country ;
    lgdo:capital_city ?city ;
    lgdo:wikipedia ?name .
}